# Basic Cleaning

In [79]:
#1. Load the CSV file using Pandas and display the first 10 rows.
import pandas as pd
import numpy as np
df = pd.read_csv("C:\\Users\\anilr\\Downloads\\messy_customer_loan_dataset - messy_customer_loan_dataset.csv")
df.head(10)

,Customer ID,Age,Annual Income,credit Score,Employment-Type,Education Level,marital_status,city,customer_segment,loan_type,Loan Amount (INR),tenure Months,Monthly Visits,debt_to_income,Loan Approved?
0,CUST101160,37,297809,698,Self-Employed,12th,Married,Mumbai,Mass,Education,378342,60,3,0.258,No
1,CUST100077,36,1048283,874,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792,48,11,0.558,Yes
2,CUST100317,55,1043481,661,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792,84,4,NaN,Yes
3,CUST101041,54,369591,722,Salaried,Graduate,Single,Kolkata,Premium,Home,908250,84,10,0.356,Yes
4,CUST101358,27,666989,727,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370,72,4,0.169,Yes
5,CUST100925,32,317590,690,Salaried,Graduate,M,Mumbai,Premium,Auto,235549,120,5,0.46,No
6,CUST100758,39,322966,707,Contract,Graduate,Married,Chennai,Mass,Personal,563319,24,7,0.323,No
7,CUST100793,54,999108,689,Salaried,Graduate,Divorced,Hyderabad,SME,Auto,767783,48,NaN,0.233,Yes
8,CUST100965,65,478191,758,Contract,Graduate,Divorced,Bengaluru,premium,Auto,753872,72,5,0.375,No
9,CUST101198,67,1063307,774,SALARIED,Graduate,Married,Jaipur,Affluent,Home,549693,120,2,0.394,Yes

In [80]:
# 2. Display the number of rows and columns in the dataset.
df.shape

(1535, 15)

In [81]:
# 3. Display all column names and identify which column names have leading/trailing spaces.
for i in df.columns:
    print(i)
    if i != i.title():
        df.rename(columns={i: i.title()}, inplace=True)

df

Customer ID
Age
Annual Income
credit Score
Employment-Type
Education  Level
marital_status
city
customer_segment
loan_type
Loan Amount (INR)
tenure Months
Monthly Visits
debt_to_income
Loan Approved?

,Customer Id,Age,Annual Income,Credit Score,Employment-Type,Education Level,Marital_Status,City,Customer_Segment,Loan_Type,Loan Amount (Inr),Tenure Months,Monthly Visits,Debt_To_Income,Loan Approved?
0,CUST101160,37,297809,698,Self-Employed,12th,Married,Mumbai,Mass,Education,378342,60,3,0.258,No
1,CUST100077,36,1048283,874,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792,48,11,0.558,Yes
2,CUST100317,55,1043481,661,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792,84,4,NaN,Yes
3,CUST101041,54,369591,722,Salaried,Graduate,Single,Kolkata,Premium,Home,908250,84,10,0.356,Yes
4,CUST101358,27,666989,727,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370,72,4,0.169,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,40,477723,719,Self-Employed,Graduate,Single,Jaipur,mass,Home Loan,1106455,48,NaN,0.569,No
1531,CUST101295,65,1394481,0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828,120,8,0.344,Yes
1532,CUST100861,66,NaN,686,Contract,Other,Married,Delhi,Mass,Personal,50000000,36,9,0.084,Yes
1533,CUST101460,45,543340,720,Business,Graduate,Married,Pune,Mass,Education,302389,72,9,0.089,No
1534,CUST101127,61,NaN,731,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995,12,5,0.259,No

In [82]:
# 4. Clean all column names by removing extra spaces and converting them into a consistent format such as snake_case.
df.columns.str.replace(" ","_",regex = True)

Index(['Customer_Id', 'Age', 'Annual_Income', 'Credit_Score',
       'Employment-Type', 'Education__Level', 'Marital_Status', 'City',
       'Customer_Segment', 'Loan_Type', 'Loan_Amount_(Inr)', 'Tenure_Months',
       'Monthly_Visits', 'Debt_To_Income', 'Loan_Approved?'],
      dtype='object')

In [83]:
# 5. Check the data type of every column.
df.dtypes

Customer Id          object
Age                  object
Annual Income        object
Credit Score         object
Employment-Type      object
Education  Level     object
Marital_Status       object
City                 object
Customer_Segment     object
Loan_Type            object
Loan Amount (Inr)    object
Tenure Months         int64
Monthly Visits       object
Debt_To_Income       object
Loan Approved?       object
dtype: object

In [84]:
# 6. Find the total number of missing values in each column.
df.isna().sum()

Customer Id            0
Age                   71
Annual Income         84
Credit Score          77
Employment-Type       60
Education  Level      46
Marital_Status         0
City                  52
Customer_Segment       0
Loan_Type              0
Loan Amount (Inr)    102
Tenure Months          0
Monthly Visits        55
Debt_To_Income        89
Loan Approved?         0
dtype: int64

In [85]:
# 7. Find the percentage of missing values in each column.
(df.isna().sum() / len(df)) * 100

Customer Id          0.000000
Age                  4.625407
Annual Income        5.472313
Credit Score         5.016287
Employment-Type      3.908795
Education  Level     2.996743
Marital_Status       0.000000
City                 3.387622
Customer_Segment     0.000000
Loan_Type            0.000000
Loan Amount (Inr)    6.644951
Tenure Months        0.000000
Monthly Visits       3.583062
Debt_To_Income       5.798046
Loan Approved?       0.000000
dtype: float64

In [86]:
# 8. Find all rows where Age is missing.
df["Age"].isnull().sum()

np.int64(71)

In [87]:
# 9. Find all rows where Annual Income is missing.
df["Annual Income"].isna().sum()

np.int64(84)

In [88]:
# 10.Remove completely duplicate rows and report how many duplicate rows were removed.
df.drop_duplicates(inplace = True)
df.duplicated().sum()

np.int64(0)

# Data Type & Invalid Values

In [89]:
# 11.The Age column contains numbers as well as values like "unknown" and
#"twenty five". Clean this column and convert it into a proper numeric column.
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Age"] = df["Age"].fillna(df["Age"].median())
abs(df["Age"].unique())

array([ 37.,  36.,  55.,  54.,  27.,  32.,  39.,  65.,  67.,  45.,  52.,
        21.,  60.,  34.,  42.,  57.,  26.,  44.,  61.,  58.,  38.,  64.,
        43.,  49.,  66.,  29.,  53.,  48.,  35.,  23.,  30.,  63.,  56.,
        22.,  47.,  25.,  62.,  41.,  24.,  40.,  51.,  59.,  50.,  33.,
        31.,  46., 105.,   5.,  28.,  12.,   3., 130.])

In [90]:
df.columns

Index(['Customer Id', 'Age', 'Annual Income', 'Credit Score',
       'Employment-Type', 'Education  Level', 'Marital_Status', 'City',
       'Customer_Segment', 'Loan_Type', 'Loan Amount (Inr)', 'Tenure Months',
       'Monthly Visits', 'Debt_To_Income', 'Loan Approved?'],
      dtype='object')

In [91]:
# 12.The Annual Income column contains values such as 650000 INR, ₹720000,
# 1.2L, and N/A. Clean the column and convert the valid values into numericformat.
df["Annual Income"].nunique()
df["Annual Income"] = pd.to_numeric(df["Annual Income"], errors = "coerce")
df['Annual Income'] = df["Annual Income"] = df["Annual Income"].fillna(df["Annual Income"].median())
df["Annual Income"].unique()
df["Annual Income"].isnull().sum()

np.int64(0)

In [92]:
# 13.Clean the Credit Score column and identify values that cannot be converted into numbers.
df["Credit Score"].isna()
df["Credit Score"] = pd.to_numeric(df["Credit Score"], errors = "coerce")
df["Credit Score"] = df["Credit Score"].fillna(df["Credit Score"].median())
abs(df["Credit Score"].isnull().sum())

np.int64(0)

In [93]:
# 14.The Loan Amount column contains currency symbols, text, and numeric
# values. Remove the unwanted characters and convert it into numeric format.
df["Loan Amount (Inr)"].isna().sum()
df["Loan Amount (Inr)"] = pd.to_numeric(df["Loan Amount (Inr)"], errors = "coerce")
df["Loan Amount (Inr)"] = df["Loan Amount (Inr)"].fillna(df["Loan Amount (Inr)"].median())
abs(df["Loan Amount (Inr)"].isna().sum())
df["Loan Amount (Inr)"].unique

<bound method Series.unique of 0         378342.0
1         751792.0
2         892792.0
3         908250.0
4         386370.0
           ...
1530     1106455.0
1531      222828.0
1532    50000000.0
1533      302389.0
1534      753995.0
Name: Loan Amount (Inr), Length: 1500, dtype: float64>

In [94]:
#  15.The Monthly Visits column contains values such as "five", "N/A", and "-".
# Convert valid values into numeric values and handle invalid values.
df["Monthly Visits"].nunique()
df["Monthly Visits"] = pd.to_numeric(df["Monthly Visits"], errors = "coerce")
df["Monthly Visits"] = df["Monthly Visits"].fillna(df["Monthly Visits"].median())
abs(df["Monthly Visits"].unique())

array([  3.,  11.,   4.,  10.,   5.,   7.,   2.,   6.,   1.,   8.,   0.,
         9.,  12.,   5.,  80.,  13., 150.,  15.])

In [95]:
# 16.Clean the Debt to Income column where some values are written like 35%
# and 0.4x. Convert the valid values into a consistent numeric format.
df["Debt_To_Income"].nunique()
df["Debt_To_Income"] = pd.to_numeric(df["Debt_To_Income"], errors = "coerce")
df["Debt_To_Income"] = df["Debt_To_Income"].fillna(df["Debt_To_Income"].median())
abs(df["Debt_To_Income"].unique())

array([0.258, 0.558, 0.343, 0.356, 0.169, 0.46 , 0.323, 0.233, 0.375,
       0.394, 0.476, 0.487, 0.494, 0.364, 0.529, 0.564, 0.303, 0.386,
       0.177, 0.353, 0.657, 0.234, 0.195, 0.333, 0.485, 0.42 , 0.231,
       0.2  , 0.291, 0.366, 0.449, 0.397, 0.287, 0.508, 0.533, 1.2  ,
       0.112, 0.327, 0.348, 0.079, 0.328, 0.653, 0.228, 0.361, 0.164,
       0.538, 0.381, 0.274, 0.741, 0.357, 0.317, 0.02 , 0.419, 0.341,
       0.304, 0.3  , 0.32 , 0.555, 0.44 , 0.552, 0.259, 0.377, 0.331,
       0.083, 0.619, 0.418, 9.   , 0.617, 0.246, 0.238, 0.308, 0.645,
       0.723, 0.354, 0.682, 0.167, 0.457, 0.31 , 0.368, 0.181, 0.241,
       0.413, 0.048, 0.268, 0.441, 0.133, 0.365, 0.402, 0.276, 0.158,
       0.352, 0.553, 0.279, 0.722, 0.193, 0.102, 0.622, 3.5  , 0.629,
       0.416, 0.199, 0.513, 0.215, 0.334, 0.29 , 0.282, 0.608, 0.426,
       0.35 , 0.115, 0.495, 0.444, 0.172, 0.596, 0.173, 0.2  , 0.252,
       0.398, 0.399, 0.031, 0.313, 0.211, 0.236, 0.423, 0.424, 0.292,
       0.261, 0.183, 0.683, 0.285, 0.321, 0.4  , 0.445, 0.464, 0.256,
       0.165, 0.408, 0.237, 0.521, 0.094, 0.383, 0.157, 0.296, 0.134,
       0.182, 0.637, 0.483, 0.493, 0.455, 0.16 , 0.251, 0.213, 0.288,
       0.509, 0.107, 0.243, 0.422, 0.325, 0.224, 0.283, 0.36 , 0.401,
       0.728, 0.492, 0.216, 0.209, 0.175, 0.545, 0.119, 0.139, 0.524,
       0.324, 0.373, 0.561, 0.219, 0.09 , 0.153, 0.459, 0.403, 0.551,
       0.454, 0.319, 0.514, 0.272, 0.411, 0.128, 0.125, 0.489, 0.143,
       0.523, 0.436, 0.269, 0.098, 0.548, 0.574, 0.472, 0.137, 0.189,
       0.567, 0.142, 0.446, 0.433, 0.388, 0.415, 0.254, 0.186, 0.203,
       0.477, 0.51 , 0.267, 0.166, 0.369, 0.121, 0.147, 0.271, 0.469,
       0.486, 0.473, 0.439, 0.748, 0.322, 0.136, 0.275, 0.295, 0.212,
       0.501, 0.382, 0.479, 0.065, 0.226, 0.385, 0.38 , 0.468, 0.185,
       0.318, 0.539, 0.5  , 0.421, 0.198, 0.248, 0.171, 0.289, 0.431,
       0.581, 0.478, 0.432, 0.335, 0.652, 0.097, 0.435, 0.376, 0.355,
       0.338, 0.222, 0.425, 0.427, 0.515, 0.417, 0.103, 0.404, 0.559,
       0.384, 0.14 , 0.18 , 0.488, 0.148, 0.161, 0.229, 0.249, 0.387,
       0.526, 0.344, 0.371, 0.255, 0.096, 0.124, 0.178, 0.482, 0.311,
       0.544, 0.24 , 0.108, 0.264, 0.37 , 0.347, 0.309, 0.463, 0.168,
       0.461, 0.442, 0.541, 0.174, 0.221, 0.242, 0.475, 0.214, 0.598,
       0.247, 0.316, 0.208, 0.277, 0.499, 0.095, 0.342, 0.326, 0.346,
       0.45 , 0.456, 0.504, 0.606, 0.122, 0.345, 0.578, 0.336, 0.359,
       0.379, 0.263, 0.497, 0.298, 0.41 , 0.618, 0.281, 0.412, 0.438,
       0.306, 0.135, 0.041, 0.106, 0.126, 0.563, 0.414, 0.23 , 0.266,
       0.245, 0.315, 0.636, 0.407, 0.075, 0.577, 0.676, 0.244, 0.48 ,
       0.329, 0.13 , 0.101, 0.151, 0.196, 0.027, 0.297, 0.536, 0.588,
       0.54 , 0.374, 0.047, 0.584, 0.451, 0.556, 0.518, 0.613, 0.081,
       0.447, 0.078, 0.12 , 0.273, 0.191, 0.428, 0.305, 0.253, 0.349,
       0.638, 0.542, 0.159, 0.516, 0.39 , 0.307, 0.698, 0.507, 0.406,
       0.512, 0.755, 0.465, 0.474, 0.301, 0.063, 0.27 , 0.184, 0.074,
       0.572, 0.57 , 0.484, 0.481, 0.284, 0.294, 0.179, 0.064, 0.207,
       0.672, 0.491, 0.503, 0.114, 0.188, 0.197, 0.156, 0.076, 0.59 ,
       0.389, 0.458, 0.648, 0.144, 0.293, 0.217, 0.235, 0.05 , 0.395,
       0.68 , 0.066, 0.339, 0.032, 0.78 , 0.19 , 0.547, 0.55 , 0.466,
       0.227, 0.358, 0.362, 0.15 , 0.084, 0.53 , 0.257, 0.367, 0.64 ,
       0.363, 0.614, 0.405, 0.129, 0.34 , 0.739, 0.332, 0.141, 0.314,
       0.537, 0.434, 0.579, 0.43 , 0.452, 0.082, 0.735, 0.554, 0.517,
       0.665, 0.605, 0.239, 0.505, 0.26 , 0.639, 0.163, 0.351, 0.534,
       0.204, 0.532, 0.378, 0.74 , 0.206, 0.569, 0.149, 0.396, 0.49 ,
       0.462, 0.409, 0.146, 0.594, 0.123, 0.67 , 0.506, 0.771, 0.21 ,
       0.372, 0.104, 0.202, 0.176, 0.691, 0.58 , 0.582, 0.635, 0.674,
       0.22 , 0.117, 0.528, 0.688, 0.392, 0.429, 0.527, 0.393, 0.17 ,
       0.28 , 0.087, 0.437, 0.225, 0.597, 0.6  , 0.059, 0.549, 0.33 ,
       0.25 , 0.089, 0.522, 0.391, 0.724, 0.337, 0.633, 0.145, 0.223,
       0.496, 0.302, 0.023, 0.651, 0.628])

In [96]:
#17.After cleaning the numerical columns, check which columns are still stored as object data type.
df.dtypes.value_counts()

object     8
float64    6
int64      1
Name: count, dtype: int64

# Categorical Cleaning

In [97]:
# 18.Find all unique values in the Employment-Type column.
df["Employment-Type"].unique()

array(['Self-Employed', 'Contract', 'Salaried', 'SALARIED',
       'Self employed', 'Business', nan, 'Unknown', 'self-employed',
       'salaried'], dtype=object)

In [98]:
# 19.Standardize the Employment-Type column so that values such as salaried, SALARIED, and Salaried become one consistent value.
df["Employment-Type"] = df["Employment-Type"].replace({"Self employed": "Self-Employed",
                                                       "self-employed": "Self-Employed",
                                                       "SALARIED": "Salaried",
                                                       "salaried": "Salaried",
                                                       "Salaried": "Salaried",
                                                       "Unknown": "nan",
                                                       "nan": "nan"
})

df["Employment-Type"].unique()

array(['Self-Employed', 'Contract', 'Salaried', 'Business', nan, 'nan'],
      dtype=object)

In [99]:
# 20.Clean the Education Level column and make values such as graduate, GRADUATE, and Graduate consistent.
df["Education  Level"] = df["Education  Level"].replace({"postgraduate": "Post Graduate",
                                                       "GRADUATE": "Graduate",
                                                       "Postgraduate": "Post Graduate",
                                                         "graduate":"Graduate"
})

df["Education  Level"].unique()

array(['12th', 'Graduate', 'Post Graduate', 'Diploma', nan, 'Other'],
      dtype=object)

In [100]:
# 21.Clean the City column. Identify incorrect or inconsistent values such as hyderbad, Hyd, Bangalore, and Bengaluru.
df["City"] = df["City"].replace({"MUMBAI": "Mumbai",
                                                         "mumbai":"Mumbai",
                                                       "hyderbad": "Hyderabad",
                                                       "Bangalore": "Bengaluru",
                                                         "Hyd":"Hyderabad",
                                                        })
df["City"].unique()

array(['Mumbai', 'Jaipur', 'Kolkata', 'Hyderabad', 'Chennai', 'Bengaluru',
       nan, 'Delhi', 'Pune'], dtype=object)

In [101]:
# 22.Find all unique values in the Customer Segment column and identify invalid categories.

df["Customer_Segment"] = df["Customer_Segment"].replace({"mass": "Mass",
                                                         "PREMIUM":"Premium",
                                                       "premium": "Premium",
                                                        })
df['Customer_Segment'].unique()

array(['Mass', 'Premium', 'Affluent', 'SME', 'unknown', 'High Value'],
      dtype=object)

In [102]:
# 23.Clean the Loan Type column so that values such as personal, PERSONAL, and personal loan are standardized.
df["Loan_Type"] = df["Loan_Type"].replace({"PERSONAL": "Personal",
                                            "auto":"Auto",
                                            "Home": "Home Loan",
                                                        })
df['Loan_Type'].unique()

array(['Education', 'Auto', 'Home Loan', 'Personal', 'Business',
       'personal loan', 'Unknown'], dtype=object)

In [103]:
df.columns

Index(['Customer Id', 'Age', 'Annual Income', 'Credit Score',
       'Employment-Type', 'Education  Level', 'Marital_Status', 'City',
       'Customer_Segment', 'Loan_Type', 'Loan Amount (Inr)', 'Tenure Months',
       'Monthly Visits', 'Debt_To_Income', 'Loan Approved?'],
      dtype='object')

In [104]:
# 24.Clean the Loan Approved column where values include Yes, yes, Y, 1, No, NO, N, and 0. Convert them into only Yes/No.

df["Loan Approved?"] = df["Loan Approved?"].replace({"NO": "No",
                                            "yes":"Yes",
                                            "0": "No",
                                            "1":"Yes",
                                            "Y":"Yes",
                                            "N":"No"
                                                        })
df['Loan Approved?'].unique()

array(['No', 'Yes', 'pending', 'approved'], dtype=object)

# Outliers & Data Validation

In [105]:
# 25.Check the Age column and identify unrealistic ages such as negative ages or ages above 100.


df['Age'] = abs(df['Age'].replace({130:99}))
df["Age"].unique()

array([ 37.,  36.,  55.,  54.,  27.,  32.,  39.,  65.,  67.,  45.,  52.,
        21.,  60.,  34.,  42.,  57.,  26.,  44.,  61.,  58.,  38.,  64.,
        43.,  49.,  66.,  29.,  53.,  48.,  35.,  23.,  30.,  63.,  56.,
        22.,  47.,  25.,  62.,  41.,  24.,  40.,  51.,  59.,  50.,  33.,
        31.,  46., 105.,   5.,  28.,  12.,   3.,  99.])

In [106]:
# 26.Check the Credit Score column and identify values outside the valid credit- score range.
df['Credit Score'].unique()
numeric_scores = pd.to_numeric(df["Credit Score"], errors="coerce")
invalid_df = df[(numeric_scores < 300) | (numeric_scores > 900) | df["Credit Score"].isna() | numeric_scores.isna()]
invalid_df

,Customer Id,Age,Annual Income,Credit Score,Employment-Type,Education Level,Marital_Status,City,Customer_Segment,Loan_Type,Loan Amount (Inr),Tenure Months,Monthly Visits,Debt_To_Income,Loan Approved?
97,CUST100644,43.0,983121.0,905.0,Contract,Graduate,Single,Jaipur,Mass,Personal,463446.0,120,4.0,0.177,Yes
113,CUST101055,44.0,1112464.0,120.0,Salaried,Diploma,Married,Kolkata,Mass,Auto,427759.0,84,3.0,0.102,No
123,CUST101109,65.0,426853.0,999.0,Contract,Diploma,Married,Delhi,Affluent,Personal,259649.0,12,10.0,0.334,Yes
295,CUST101220,41.0,442392.0,250.0,Business,Diploma,Married,Delhi,Affluent,Auto,50000000.0,72,9.0,0.275,Yes
296,CUST100745,58.0,1044693.0,0.0,Business,Post Graduate,Married,Bengaluru,Affluent,Auto,442037.0,36,3.0,0.261,No
342,CUST100255,52.0,402265.0,120.0,Business,Diploma,Married,NaN,Mass,Home Loan,442037.0,36,9.0,0.376,Yes
542,CUST100909,38.0,778215.0,120.0,Business,12th,Married,Mumbai,Affluent,Personal,997263.0,48,2.0,0.343,Yes
680,CUST100666,53.0,680059.0,120.0,Contract,Graduate,Married,Delhi,Premium,Personal,116706.0,72,1.0,0.512,No
710,CUST100046,66.0,276121.0,0.0,Business,Other,unknown,Chennai,Premium,Auto,877671.0,48,1.0,0.263,Yes
726,CUST100922,47.0,827522.0,903.0,Salaried,Post Graduate,Married,Delhi,Premium,Home Loan,355150.0,120,3.0,0.207,Yes
807,CUST100937,28.0,783241.0,120.0,Contract,Graduate,Married,Kolkata,Mass,Home Loan,266100.0,120,5.0,0.112,Yes
927,CUST100824,51.0,618064.0,250.0,Contract,Graduate,Single,Hyderabad,Mass,Personal,183673.0,12,2.0,0.335,No
930,CUST100508,32.0,646827.0,0.0,Contract,12th,Single,Bengaluru,SME,Business,525860.0,24,3.0,0.343,Yes
959,CUST100876,44.0,807700.0,0.0,Business,Post Graduate,Married,Hyderabad,Mass,Home Loan,272420.0,60,5.0,0.353,Yes
964,CUST100070,43.0,604540.0,120.0,Salaried,12th,Single,Jaipur,Affluent,Home Loan,1603055.0,12,6.0,0.334,No
1082,CUST100690,57.0,831564.0,0.0,Business,Post Graduate,Married,Mumbai,Premium,Business,536613.0,60,5.0,0.534,Yes
1159,CUST100444,43.0,315278.0,250.0,Self-Employed,Graduate,Married,Bengaluru,Affluent,Business,700803.0,36,8.0,0.336,No
1217,CUST100302,59.0,646827.0,250.0,Contract,Graduate,Married,Pune,Mass,Personal,625206.0,84,5.0,0.252,Yes
1232,CUST101284,58.0,733526.0,250.0,Business,Graduate,Married,Pune,Affluent,Personal,204868.0,120,6.0,0.449,No
1286,CUST101378,56.0,441775.0,120.0,Self-Employed,Graduate,Single,Bengaluru,Mass,Business,1153676.0,60,2.0,0.564,Yes
1288,CUST100453,44.0,614537.0,0.0,Salaried,Graduate,Married,Jaipur,Mass,Business,328075.0,60,4.0,0.377,No
1352,CUST101407,37.0,1874514.0,250.0,Contract,Graduate,Married,Mumbai,Premium,Personal,539352.0,12,12.0,0.300,No
1461,CUST101414,58.0,759405.0,120.0,Salaried,NaN,Single,Jaipur,Premium,Auto,366567.0,120,4.0,0.291,Yes
1531,CUST101295,65.0,1394481.0,0.0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344,Yes

In [107]:
df.columns

Index(['Customer Id', 'Age', 'Annual Income', 'Credit Score',
       'Employment-Type', 'Education  Level', 'Marital_Status', 'City',
       'Customer_Segment', 'Loan_Type', 'Loan Amount (Inr)', 'Tenure Months',
       'Monthly Visits', 'Debt_To_Income', 'Loan Approved?'],
      dtype='object')

In [108]:
# 27.Detect outliers in Annual Income using the IQR method.

Q1 = df["Annual Income"].quantile(0.25)
Q3 = df["Annual Income"].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
lower_bound
upper_bound = Q3 + 1.5 * IQR
upper_bound

outliers_df = df[(df["Annual Income"] < lower_bound) | (df["Annual Income"] > upper_bound)]
outliers_df

,Customer Id,Age,Annual Income,Credit Score,Employment-Type,Education Level,Marital_Status,City,Customer_Segment,Loan_Type,Loan Amount (Inr),Tenure Months,Monthly Visits,Debt_To_Income,Loan Approved?
14,CUST101158,60.0,1548824.0,698.0,Contract,Graduate,Married,Pune,SME,Home Loan,333121.0,24,10.0,0.529,No
18,CUST100050,57.0,1457160.0,687.0,Business,12th,Divorced,Kolkata,Affluent,Home Loan,258267.0,12,4.0,0.343,Yes
19,CUST100241,27.0,1412437.0,637.0,Business,Post Graduate,Married,Mumbai,Affluent,Education,752049.0,48,4.0,0.386,Yes
61,CUST100757,55.0,1777657.0,666.0,Contract,Post Graduate,Single,Hyderabad,Premium,Education,900253.0,72,3.0,0.304,Yes
74,CUST100238,41.0,1907548.0,678.0,Business,Graduate,Single,Mumbai,Mass,Business,242378.0,72,0.0,0.343,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1466,CUST100206,33.0,1604257.0,785.0,Contract,12th,Single,Mumbai,Affluent,Business,442037.0,24,3.0,0.355,No
1467,CUST100035,62.0,1531271.0,779.0,Business,Post Graduate,Single,Hyderabad,Mass,Personal,327941.0,24,4.0,0.179,Yes
1511,CUST101216,26.0,1403890.0,716.0,NaN,Graduate,Single,Pune,Mass,Home Loan,328004.0,72,6.0,0.050,approved
1515,CUST100344,45.0,80000000.0,819.0,Self-Employed,Post Graduate,Single,Mumbai,Mass,Personal,636933.0,12,6.0,0.384,Yes
1531,CUST101295,65.0,1394481.0,0.0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344,Yes

In [110]:
# 28.Detect outliers in Loan Amount using the IQR method.
Q1 = df["Loan Amount (Inr)"].quantile(0.25)
Q3 = df["Loan Amount (Inr)"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[
    (df["Loan Amount (Inr)"] < lower_bound) |
    (df["Loan Amount (Inr)"] > upper_bound)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)
print("Number of Outliers:", len(outliers))
print(outliers)

Q1: 297100.5
Q3: 654682.75
IQR: 357582.25
Lower Bound: -239272.875
Upper Bound: 1191056.125
Number of Outliers: 100
     Customer Id   Age  Annual Income  Credit Score Employment-Type  \
11    CUST100679  45.0       856826.0         662.0   Self-Employed
25    CUST100071  58.0       454340.0         743.0        Business
58    CUST100345  63.0       477076.0         785.0        Salaried
99    CUST100661  29.0      1170831.0         734.0        Salaried
110   CUST100030  41.0       423380.0         787.0        Business
...          ...   ...            ...           ...             ...
1439  CUST100764  64.0       761542.0         731.0             NaN
1469  CUST100509  33.0       850268.0         829.0        Business
1476  CUST100565  62.0       669143.0         739.0        Business
1501  CUST100475  50.0       646827.0         802.0        Contract
1532  CUST100861  66.0       646827.0         686.0        Contract

     Education  Level Marital_Status       City Customer_Segment  Loan_Type  \
11      Post Graduate       Divorced        NaN         Affluent  Education
25           Graduate         Single     Jaipur          Premium   Business
58           Graduate        MARRIED    Chennai              SME  Education
99           Graduate        Married    Chennai             Mass       Auto
110     Post Graduate        Married     Jaipur          Premium   Business
...               ...            ...        ...              ...        ...
1439         Graduate        MARRIED  Bengaluru             Mass       Auto
1469              NaN        Married    Kolkata             Mass   Personal
1476         Graduate         Single    Chennai          Premium   Personal
1501             12th       Divorced    Kolkata             Mass   Personal
1532            Other        Married      Delhi             Mass   Personal

      Loan Amount (Inr)  Tenure Months  Monthly Visits  Debt_To_Income  \
11            1412363.0             12             5.0           0.487
25            1545154.0             72             3.0           0.333
58            1575763.0             24             8.0           0.419
99            1193415.0            120             5.0           0.441
110           1266643.0             36             3.0           0.722
...                 ...            ...             ...             ...
1439          2170814.0             72             2.0           0.247
1469          1647932.0             72             4.0           0.329
1476          1257561.0             24             4.0           0.374
1501          1488587.0             36             5.0           0.023
1532         50000000.0             36             9.0           0.084

     Loan Approved?
11              Yes
25              Yes
58               No
99              Yes
110             Yes
...             ...
1439            Yes
1469            Yes
1476             No
1501            Yes
1532            Yes

[100 rows x 15 columns]

In [111]:
# 29.Check the Debt to Income column and identify impossible values such as negative values or values greater than 1.
print(df.loc[
    (df["Debt_To_Income"] < 0) |
    (df["Debt_To_Income"] > 1),
    "Debt_To_Income"
])

31     -0.2
39      1.2
77      9.0
115     3.5
278     3.5
486     3.5
573     1.2
796     3.5
941     9.0
1048    1.2
1107    1.2
1177    9.0
1296    9.0
1353    1.2
1390    9.0
1425   -0.2
1463   -0.2
1524    3.5
Name: Debt_To_Income, dtype: float64

In [116]:
df.columns

Index(['customer_id', 'age', 'annual_income', 'credit_score',
       'employment_type', 'education__level', 'marital_status', 'city',
       'customer_segment', 'loan_type', 'loan_amount_(inr)', 'tenure_months',
       'monthly_visits', 'debt_to_income', 'loan_approved?'],
      dtype='object')